Hw2
Daniel-Rue/tinkoff-java-course-2024-backend pull request #2
Opened 2024-02-23 17:17 UTC by Daniel-Rue

2024-02-28 18:51 UTC, IvanAksenov11 requested changes

2024-02-28 18:51 UTC, IvanAksenov11 commented on scrapper/src/test/java/edu/java/scrapper/SampleTest.java
> +public class SampleTest {
а зачем это сэмпл тащить в репозиторий?
Тут же реально нет никаких проверок

2024-02-28 18:51 UTC, IvanAksenov11 commented on scrapper.zip
а что здесь?

2024-02-28 18:51 UTC, IvanAksenov11 commented on bot/src/main.zip
а что здесь?

2024-02-28 22:24 UTC, Daniel-Rue commented on scrapper/src/test/java/edu/java/scrapper/SampleTest.java
> +public class SampleTest {
Удалил

2024-02-28 22:24 UTC, Daniel-Rue commented on scrapper.zip
Случайно оставил архивы папок. Удалил

2024-02-29 17:06 UTC, IvanAksenov11 approved these changes

2024-03-01 08:30 UTC, merged